version: "3"
services:
  elasticsearchJSON:
    platform: linux/x86_64
    image: elasticsearch:7.6.2
    container_name: elasticsearchJSON
    hostname: elasticsearchJSON
    restart: always
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - dockerelk
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstashJSON:
    platform: linux/x86_64
    image: logstash:7.6.2
    container_name: logstashJSON
    hostname: logstashJSON
    ports:
      - 9600:9600
      - 8089:8089
    restart: always
    links:
      - elasticsearchJSON:elasticsearchJSON
    depends_on:
      - elasticsearchJSON
    networks:
      - dockerelk
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./data/data-json.log:/usr/share/logstash/external-data/data-json.log    # JSON data

  kibanaJSON:
    platform: linux/x86_64
    image: kibana:7.6.2
    container_name: kibanaJSON
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearchJSON:9200
    ports:
      - "5601:5601"
    networks:
      - dockerelk
    depends_on:
      - elasticsearchJSON

networks:
  dockerelk:
    driver: bridge